### ISSUE TITLE
Initialize Git?

### ISSUE THREAD

**Issue by brasilikum** [rogeriochaves/spades#23]
First off: Thanks for creating this @rogeriochaves, I only played around with it so far but it definitely takes away so much work!

I think it would be a good thing to initialize git and do the initial commit.
This way you can easily revert after playing with some commands.
I find it reasonably enough that people are using git.
If they don't, they can still do `rm -rf .git`

**Comment by rogeriochaves** [comment]
Thank you! I totally agree, specially with "This way you can easily revert after playing with some commands", I found myself doing that some times with other boilerplates and wanting to understand what was the baseline and what was the thing I just changed

I've implemented this on 548a96c9fbe2e33fa78420921451a9947f0025e1
