### ISSUE TITLE
Debugger and auto-recompile on file change

### ISSUE THREAD

**Issue by pienter-tech** [rogeriochaves/spades#27]
Hello, 
For starters: I really love the generators!
But I'm missing two things in this project:
- When using `npm start` the debugger should be on by default.  
  I added this: 
  ```
    use: [{
          loader: 'elm-webpack-loader',
          options: {
            verbose: true,
            debug: true,
          },
        }],
  ```  
  to the webpack.config.js but when I want to build I always have to remember to change the options.
- Right now when I update the elm code I always have to stop and rerun `npm start`   
  it would be nice if there was a file watcher to recompile automatically.

**Comment by tigp** [comment]
This is only true for --serverless config

**Comment by Maxim-Filimonov** [comment]
@tigp is it possible to get HMR without `--serverless` config? I'd like to get both SSR and HMR

**Comment by rogeriochaves** [comment]
sorry for the looong delay, I've fixed to now recompile also the version with a server on #32, it's not hot though, if anybody wants to work on that feel free, I'll open another issue for that: #33

**Comment by rogeriochaves** [comment]
@Maxim-Filimonov there is the webpack-hot-middleware to use on the server, but I haven't had time to play with it yet
