### ISSUE TITLE
npm install hanging on  binwrap-install

### ISSUE THREAD

**Issue by sevfurneaux** [rogeriochaves/spades#28]
When I run `npm install`, it seems to be hanging on `binwrap-install`. Seems to be a similar issue to https://github.com/avh4/elm-format/issues/377.

Have you experienced this yourself?

**Comment by sevfurneaux** [comment]
Seems to be working ok now 👍

**Comment by erlandsona** [comment]
I'm having this issue on Pop!_OS (Ubuntu Linux)... did you do anything special to fix this?

**Comment by erlandsona** [comment]
Nvmd... `npm i -g npm`
